// GENERATED FILE — DO NOT EDIT BY HAND.
// Source of truth: the four-pass scan of handoff/components/** + handoff/ui_kits/**.
// Regenerate: `node tools/icon-registry/generate.mjs`  (drift-guarded by `--check`).
// RCT-05: curated, tree-shakable, no-CDN icon surface (78 lucide-react imports + 1 vendored).

import {
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bell,
  BookOpen,
  Calendar,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleX,
  CloudUpload,
  Code,
  Copy,
  CreditCard,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  File,
  FileArchive,
  FilePlus,
  FileSpreadsheet,
  FileText,
  Film,
  Filter,
  Folder,
  FolderOpen,
  Globe,
  HardDrive,
  Heart,
  House,
  Image,
  Inbox,
  Info,
  LayoutDashboard,
  LayoutGrid,
  Link,
  List,
  Lock,
  LogOut,
  Mail,
  MessageCircle,
  Minus,
  Moon,
  Music,
  Package,
  Pencil,
  Plus,
  Rocket,
  Scale,
  Search,
  Send,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Timer,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  Zap,
  createLucideIcon,
  type LucideIcon,
} from 'lucide-react';

// `github` is vendored: brand icons were removed from lucide-react in v1.0.
// vendored icon path data (ISC) — provenance documented in the generator.
const Github = createLucideIcon('github', [
  ['path', { d: 'M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4', key: 'gh1' }],
  ['path', { d: 'M9 18c-4.51 2-5-2-7-2', key: 'gh2' }],
]);

export const iconRegistry = {
  'archive': Archive,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'bell': Bell,
  'book-open': BookOpen,
  'calendar': Calendar,
  'chart-line': ChartLine,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up-down': ChevronsUpDown,
  'circle': Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dot': CircleDot,
  'circle-x': CircleX,
  'cloud-upload': CloudUpload,
  'code': Code,
  'copy': Copy,
  'credit-card': CreditCard,
  'download': Download,
  'ellipsis': Ellipsis,
  'external-link': ExternalLink,
  'eye': Eye,
  'file': File,
  'file-archive': FileArchive,
  'file-plus': FilePlus,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'film': Film,
  'filter': Filter,
  'folder': Folder,
  'folder-open': FolderOpen,
  'github': Github,
  'globe': Globe,
  'hard-drive': HardDrive,
  'heart': Heart,
  'house': House,
  'image': Image,
  'inbox': Inbox,
  'info': Info,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'link': Link,
  'list': List,
  'lock': Lock,
  'log-out': LogOut,
  'mail': Mail,
  'message-circle': MessageCircle,
  'minus': Minus,
  'moon': Moon,
  'music': Music,
  'package': Package,
  'pencil': Pencil,
  'plus': Plus,
  'rocket': Rocket,
  'scale': Scale,
  'search': Search,
  'send': Send,
  'settings': Settings,
  'shield': Shield,
  'sliders-horizontal': SlidersHorizontal,
  'sparkles': Sparkles,
  'star': Star,
  'sun': Sun,
  'terminal': Terminal,
  'timer': Timer,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  'upload': Upload,
  'user': User,
  'user-plus': UserPlus,
  'users': Users,
  'x': X,
  'zap': Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
